# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

def common_pod_dependencies
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    #Tools
    pod 'SwiftLint', '~> 0.20'
    pod 'Sourcery', '~> 0.7'
    pod 'SwiftGen'
end

def app_dependencies
    # Pods for PlaylistBot
    pod 'Hero', '~> 1.0'

    #Debugging Tools
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    pod 'LifetimeTracker', :git => 'git@github.com:krzysztofzablocki/LifetimeTracker.git', :branch => 'master', :configurations => ['Debug']
    pod 'JRSwizzle', :configurations => ['Debug']
end

def test_dependencies
    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
    pod 'RxTest', '~> 4.0'
end

target 'PlaylistBuilder' do
    use_frameworks!
    common_pod_dependencies

    target 'PlaylistBuilderTests' do
        inherit! :search_paths
        test_dependencies
    end
end

target 'PlaylistBot' do
    use_frameworks!
    common_pod_dependencies
    app_dependencies

    target 'PlaylistBotTests' do
        inherit! :search_paths
        test_dependencies
    end

    target 'PlaylistBotUITests' do
        inherit! :search_paths
        test_dependencies
    end

end
